### ISSUE TITLE
Wrong warning for missing DrillDownPageID/LookupPageID 

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/vscode-allint#12]
When there are comment lines inside the table environment before the table properties. The warning about missing DrillDownPageID and LookupPageID is still shown.
![image](https://user-images.githubusercontent.com/56249171/95575238-9cc71c00-0a2e-11eb-9229-662c29a84366.png)

**Comment by StefanMaron** [comment]
Please check if the issue still exists in version 0.2.4

**Comment by pri-kise** [comment]
LGTM
